# Generated by Django 2.1.3 on 2018-11-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20181125_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
