# Generated by Django 2.1.3 on 2018-11-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
